### ISSUE TITLE
Rainbow not working

### ISSUE THREAD

**Issue by kd8bxp** [CyntechUK/WeatherHAT#3]
Tried on a Raspberry PI 3 and Raspberry PI Zero W - with 2017-07-05-Raspbian-Jessie
All the leds work with the exception of the rainbow.
Tried a previous version - that used the unicorn hat driver - (commit: 0a0b391ea7d70a191863c6de0a39d4844b286863) and the rainbow worked - but flashed a lot.

**Comment by Boeeerb** [comment]
The Raspberry Pi 3 messed up timings for Neopixels due to a change in the audio PWM - Try the changes in the config.txt as shown here;
http://guides.cyntech.co.uk/raspberry-pi/assembling-the-word-clock/#Setting_up_software

**Comment by kd8bxp** [comment]
Thank you, this worked.
